name: BumpMainVersion
run-name: ${{ github.actor }} requested version increase for main
on:
  workflow_dispatch:
    inputs:
      next_version_type:
        description: 'The next version type'
        required: true
        type: choice
        default: Minor
        options:
          - Minor
          - Major

jobs:
  bump-main-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install replace -g
      - run: git config --global user.email "moyarsuccess@gmail.com"
      - run: git config --global user.name "Moyar"
      - run: MAJOR=$(grep 'const val major =' app/src/main/java/com/moradyar/githubactions/AppVersion.kt | rev | cut -d' ' -f1 | rev)
      - run: MINOR=$(grep 'const val minor =' app/src/main/java/com/moradyar/githubactions/AppVersion.kt | rev | cut -d' ' -f1 | rev)
      - run: PATCH=$(grep 'const val patch =' app/src/main/java/com/moradyar/githubactions/AppVersion.kt | rev | cut -d' ' -f1 | rev)
      - run: |
          if [[ ${{ github.event.inputs.next_version_type }} -eq Major ]]
          then
            NEW_MAJOR=$(($MAJOR + 1))
            versionName=release/$NEW_MAJOR.$MINOR.$PATCH
          else
            NEW_MINOR=$(($MINOR + 1))
            versionName=release/$MAJOR.$NEW_MINOR.$PATCH
      - run: git checkout -b $versionName
      - run: |    
          if [[ ${{ github.event.inputs.next_version_type }} -eq Major ]]
          then
            replace "const val major = $MAJOR" "const val rcVersion = $NEW_MAJOR" app/src/main/java/com/moradyar/githubactions/AppVersion.kt
          else
            replace "const val minor = $MINOR" "const val rcVersion = $NEW_MINOR" app/src/main/java/com/moradyar/githubactions/AppVersion.kt
      - run: git add -A
      - run: git commit -m "Release a new RC"
      - run: git push --set-upstream origin $versionName