name: BumpRcVersion
run-name: ${{ github.actor }} bumped the RC version

on:
  push:
    branches:
      - 'release/*'

jobs:
  bump-rc-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install replace -g
      - run: |
          version=$(grep 'const val rcVersion =' app/src/main/java/com/moradyar/githubactions/AppVersion.kt | rev | cut -d' ' -f1 | rev)
          newVersion=$(($version + 1))
          replace "const val rcVersion = $version" "const val rcVersion = $newVersion" app/src/main/java/com/moradyar/githubactions/AppVersion.kt
          git config --global user.email "moyarsuccess@gmail.com"
          git config --global user.name "Moyar"
          git add -A
          git commit -m "Bump the version"
          git push
          tagName="$versionName.RC.$newVersion"
          git tag -a $tagName -m "Tag a new RC $tagName"
          git push --set-upstream origin $tagName