name: BumpRcVersion
run-name: ${{ github.actor }} bumped the RC version
on:
  workflow_dispatch:

jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    env:
      FILE_NAME: app/src/main/java/com/moradyar/githubactions/AppVersion.kt
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install replace -g
      - run: |
          VERSION=$(grep 'const val rcVersion =' $FILE_NAME | rev | cut -d' ' -f1 | rev)
          echo $VERSION
          NEW_VERSION=VERSION + 1
          echo $NEW_VERSION
          replace 'const val rcVersion = $VERSION' 'const val rcVersion = NEW_VERSION' $FILE_NAME
      - run: |
          git config --global user.email "moyarsuccess@gmail.com"
          git config --global user.name "Moyar"
          git add -A
          git commit -m "Bump the version"
          git push --set-upstream origin release/${{ inputs.major_version }}.${{ inputs.minor_version }}.${{ inputs.patch_version }}