name: Release Build

on:
  workflow_call:
    inputs:
      branchName:
        required: true
        type: string

jobs:
  test_job:
    name: Unit Tests
    runs-on: ubuntu-latest
    continue-on-error: true
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.branchName }}
      - run: echo "Distributed!"
