name: Release Build

on:
  workflow_call:

jobs:
  test_job:
    name: Unit Tests
    runs-on: ubuntu-latest
    continue-on-error: true
    timeout-minutes: 20
    steps:
      - run: echo "Distributed!"
