name: Publish Release

on:
  workflow_call:

jobs:
  publish_job:
    name: Publish
    runs-on: ubuntu-latest
    continue-on-error: true
    timeout-minutes: 20
    steps:
      - run: echo "Published!"

