name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on:
  workflow_dispatch:
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install replace -g
      - run: replace 'version = 1' 'version = 2' app/src/main/java/com/moradyar/githubactions/AppVersion.kt
      - run: |
            git config --global user.email "moyarsuccess@gmail.com"
            git config --global user.name "Moyar"
            git add -A
            git commit -m "Bump the version"
            git push