name: ReleaseRc
run-name: ${{ github.actor }} started a new RC
on:
  workflow_dispatch:
    inputs:
      major_version:
        description: 'Major version'
        required: true
        type: string

      minor_version:
        description: 'Minor version'
        required: true
        type: string

      patch_version:
        description: 'Patch version'
        required: true
        type: string

jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install replace -g
      - run: |
          git config --global user.email "moyarsuccess@gmail.com"
          git config --global user.name "Moyar"
          versionName=release/${{ inputs.major_version }}.${{ inputs.minor_version }}.${{ inputs.patch_version }}
          git checkout -b $versionName
          replace 'isRc = false' 'isRc = true' app/src/main/java/com/moradyar/githubactions/AppVersion.kt
          git add -A
          git commit -m "Release a new RC"
          git push --set-upstream origin $versionName