name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on:
  workflow_dispatch:
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install replace -g
      - run: replace 'version = 1' 'version = 2' app/src/main/java/com/moradyar/githubactions/AppVersion.kt
      - name: git
        - run: git add -A
        - run: git commit -m "Bump the version"
        - run: git push